extern void set_input(char *pad_key);
extern void clear_input(char *pad_key);
extern void reset_input();
extern int pad1_DOWN;
extern int pad1_UP;
extern int pad1_LEFT;
extern int pad1_RIGHT;
extern int pad1_START;
extern int pad1_SELECT;
extern int pad1_A;
extern int pad1_B;
