extern unsigned char memory_read(unsigned int address);
extern void write_memory(unsigned int address,unsigned char data);
extern void set_input();
extern void reset_emulation();
extern void quit_emulation();
extern char romfn[256];
extern unsigned char *romcache;
extern unsigned char *ppu_memory;
extern int CPU_is_running;
extern int height;
extern int width;
extern int sdl_screen_height;
extern int sdl_screen_width;
extern long romlen;
